### ISSUE TITLE
Automatic date change before page loading

### ISSUE THREAD

**Issue by icarocd** [KeshiaRose/Date-Updater#1]
Hi.
Nice job on this.
I wonder if we can change the date before the page is loaded, so that we can avoid page reloading and 2x query execution.
Thanks in advance.

**Comment by KeshiaRose** [comment]
Hi @icarocd,

Unfortunately, all extensions run after the dashboard is loaded because it may need access to the data. Therefore there is no way to avoid the double load 😞. 

One thing you could do is set your parameter to something that wouldn't load any data when you save the workbook and that way the first load is quick since nothing is returned and then it loads the real data once the parameter is updated. 

Also, this is a verrrrrryyyy old project. Please use the official extension I created that is much better, you can find it in the [gallery](https://extensiongallery.tableau.com/products/28).

Take care,
Keshia
